version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: image_embeddings
    ports:
      - "6333:6333"
    volumes:
      - ./storage:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: INFO
