version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_container
    ports:
      - "6333:6333"
    volumes:
      - ./storage:/qdrant_storage/storage
    environment:
      QDRANT__LOG_LEVEL: INFO
